const rawData = [
  { "department": "Ain (01)", "president": "Jean Deguerry", "party": "LR", "population": 663205, "budget": "760 M€" },
  { "department": "Aisne (02)", "president": "Nicolas Fricoteaux", "party": "UDI", "population": 527129, "budget": "610 M€" },
  { "department": "Allier (03)", "president": "Claude Riboulet", "party": "UDI", "population": 334872, "budget": "385 M€" },
  { "department": "Alpes-de-Haute-Provence (04)", "president": "Eliane Barreille", "party": "LR", "population": 165451, "budget": "190 M€" },
  { "department": "Hautes-Alpes (05)", "president": "Jean-Marie Bernard", "party": "LR", "population": 140974, "budget": "165 M€" },
  { "department": "Alpes-Maritimes (06)", "president": "Charles-Ange Ginesy", "party": "LR", "population": 1103941, "budget": "1.25 B€" },
  { "department": "Ardèche (07)", "president": "Olivier Amrane", "party": "LR", "population": 331415, "budget": "380 M€" },
  { "department": "Ardennes (08)", "president": "Noël Bourgeois", "party": "LR", "population": 268859, "budget": "310 M€" },
  { "department": "Ariège (09)", "president": "Christine Téqui", "party": "PS", "population": 154532, "budget": "180 M€" },
  { "department": "Aube (10)", "president": "Philippe Pichery", "party": "DVD", "population": 311876, "budget": "360 M€" },
  { "department": "Aude (11)", "president": "Hélène Sandragné", "party": "PS", "population": 376028, "budget": "430 M€" },
  { "department": "Aveyron (12)", "president": "Arnaud Viala", "party": "LR", "population": 279649, "budget": "320 M€" },
  { "department": "Bouches-du-Rhône (13)", "president": "Martine Vassal", "party": "DVD", "population": 2048350, "budget": "2.85 B€" },
  { "department": "Calvados (14)", "president": "Jean-Léonce Dupont", "party": "LC", "population": 700633, "budget": "810 M€" },
  { "department": "Cantal (15)", "president": "Bruno Faure", "party": "LR", "population": 144229, "budget": "170 M€" },
  { "department": "Charente (16)", "president": "Philippe Bouty", "party": "DVG", "population": 350867, "budget": "405 M€" },
  { "department": "Charente-Maritime (17)", "president": "Sylvie Marcilly", "party": "DVD", "population": 661404, "budget": "760 M€" },
  { "department": "Cher (18)", "president": "Jacques Fleury", "party": "LR", "population": 299573, "budget": "345 M€" },
  { "department": "Corrèze (19)", "president": "Pascal Coste", "party": "LR", "population": 239784, "budget": "275 M€" },
  { "department": "Corse-du-Sud (2A)", "president": "Pierre-Jean Luciani", "party": "DVD", "population": 162942, "budget": "190 M€" },
  { "department": "Haute-Corse (2B)", "president": "François Orlandi", "party": "PRG", "population": 184655, "budget": "215 M€" },
  { "department": "Côte-d'Or (21)", "president": "François Sauvadet", "party": "UDI", "population": 535503, "budget": "620 M€" },
  { "department": "Côtes-d'Armor (22)", "president": "Christian Coail", "party": "PS", "population": 605917, "budget": "700 M€" },
  { "department": "Creuse (23)", "president": "Valérie Simonet", "party": "LR", "population": 115702, "budget": "135 M€" },
  { "department": "Dordogne (24)", "president": "Germinal Peiro", "party": "PS", "population": 413223, "budget": "475 M€" },
  { "department": "Doubs (25)", "president": "Christine Bouquin", "party": "DVD", "population": 547184, "budget": "630 M€" },
  { "department": "Drôme (26)", "president": "Marie-Pierre Mouton", "party": "LR", "population": 519458, "budget": "600 M€" },
  { "department": "Eure (27)", "president": "Alexandre Rassaërt", "party": "DVD", "population": 598934, "budget": "690 M€" },
  { "department": "Eure-et-Loir (28)", "president": "Christophe Le Dorven", "party": "LR", "population": 431277, "budget": "500 M€" },
  { "department": "Finistère (29)", "president": "Maël de Calan", "party": "DVD", "population": 921638, "budget": "1.06 B€" },
  { "department": "Gard (30)", "president": "Françoise Laurent-Perrigot", "party": "PS", "population": 756543, "budget": "870 M€" },
  { "department": "Haute-Garonne (31)", "president": "Sébastien Vincini", "party": "PS", "population": 1434367, "budget": "1.65 B€" },
  { "department": "Gers (32)", "president": "Philippe Dupouy", "party": "PS", "population": 192437, "budget": "225 M€" },
  { "department": "Gironde (33)", "president": "Jean-Luc Gleyze", "party": "PS", "population": 1654970, "budget": "1.95 B€" },
  { "department": "Hérault (34)", "president": "Kléber Mesquida", "party": "PS", "population": 1201883, "budget": "1.40 B€" },
  { "department": "Ille-et-Vilaine (35)", "president": "Jean-Luc Chenut", "party": "PS", "population": 1098325, "budget": "1.30 B€" },
  { "department": "Indre (36)", "president": "Marc Fleuret", "party": "LR", "population": 217228, "budget": "250 M€" },
  { "department": "Indre-et-Loire (37)", "president": "Jean-Gérard Paumier", "party": "LR", "population": 612160, "budget": "710 M€" },
  { "department": "Isère (38)", "president": "Jean-Pierre Barbier", "party": "LR", "population": 1284948, "budget": "1.50 B€" },
  { "department": "Jura (39)", "president": "Clément Pernot", "party": "LR", "population": 258555, "budget": "300 M€" },
  { "department": "Landes (40)", "president": "Xavier Fortinon", "party": "PS", "population": 421795, "budget": "490 M€" },
  { "department": "Loir-et-Cher (41)", "president": "Philippe Gouet", "party": "UDI", "population": 328541, "budget": "380 M€" },
  { "department": "Loire (42)", "president": "Georges Ziegler", "party": "LR", "population": 769305, "budget": "890 M€" },
  { "department": "Haute-Loire (43)", "president": "Marie-Agnès Petit", "party": "LR", "population": 227745, "budget": "265 M€" },
  { "department": "Loire-Atlantique (44)", "president": "Michel Ménard", "party": "PS", "population": 1457806, "budget": "1.70 B€" },
  { "department": "Loiret (45)", "president": "Marc Gaudet", "party": "UDI", "population": 684195, "budget": "790 M€" },
  { "department": "Lot (46)", "president": "Serge Rigal", "party": "DVG", "population": 174094, "budget": "205 M€" },
  { "department": "Lot-et-Garonne (47)", "president": "Sophie Borderie", "party": "PS", "population": 331229, "budget": "385 M€" },
  { "department": "Lozère (48)", "president": "Sophie Pantel", "party": "PS", "population": 76519, "budget": "110 M€" },
  { "department": "Maine-et-Loire (49)", "president": "Florence Dabin", "party": "DVD", "population": 824743, "budget": "955 M€" },
  { "department": "Manche (50)", "president": "Jean Morin", "party": "DVD", "population": 495508, "budget": "575 M€" },
  { "department": "Marne (51)", "president": "Christian Bruyen", "party": "DVD", "population": 565292, "budget": "655 M€" },
  { "department": "Haute-Marne (52)", "president": "Nicolas Lacroix", "party": "LR", "population": 171042, "budget": "200 M€" },
  { "department": "Mayenne (53)", "president": "Olivier Richefou", "party": "UDI", "population": 305933, "budget": "355 M€" },
  { "department": "Meurthe-et-Moselle (54)", "president": "Chaynesse Khirouni", "party": "PS", "population": 732486, "budget": "850 M€" },
  { "department": "Meuse (55)", "president": "Jérôme Dumont", "party": "DVD", "population": 181919, "budget": "215 M€" },
  { "department": "Morbihan (56)", "president": "David Lappartient", "party": "DVD", "population": 768689, "budget": "890 M€" },
  { "department": "Moselle (57)", "president": "Patrick Weiten", "party": "UDI", "population": 1049942, "budget": "1.20 B€" },
  { "department": "Nièvre (58)", "president": "Fabien Bazin", "party": "PS", "population": 202417, "budget": "235 M€" },
  { "department": "Nord (59)", "president": "Christian Poiret", "party": "DVD", "population": 2611293, "budget": "3.55 B€" },
  { "department": "Oise (60)", "president": "Nadège Lefebvre", "party": "LR", "population": 829839, "budget": "960 M€" },
  { "department": "Orne (61)", "president": "Christophe de Balorre", "party": "LR", "population": 276973, "budget": "320 M€" },
  { "department": "Pas-de-Calais (62)", "president": "Jean-Claude Leroy", "party": "PS", "population": 1461441, "budget": "1.75 B€" },
  { "department": "Puy-de-Dôme (63)", "president": "Lionel Chauvin", "party": "LR", "population": 662285, "budget": "765 M€" },
  { "department": "Pyrénées-Atlantiques (64)", "president": "Jean-Jacques Lasserre", "party": "MoDem", "population": 693027, "budget": "800 M€" },
  { "department": "Hautes-Pyrénées (65)", "president": "Michel Pélieu", "party": "PRG", "population": 230956, "budget": "270 M€" },
  { "department": "Pyrénées-Orientales (66)", "president": "Hermeline Malherbe", "party": "PS", "population": 487338, "budget": "565 M€" },
  { "department": "Bas-Rhin (67)", "president": "Frédéric Bierry", "party": "LR", "population": 1152662, "budget": "1.35 B€" },
  { "department": "Haut-Rhin (68)", "president": "Frédéric Bierry", "party": "LR", "population": 767083, "budget": "890 M€" },
  { "department": "Rhône (69)", "president": "Christophe Guilloteau", "party": "LR", "population": 468453, "budget": "545 M€" },
  { "department": "Métropole de Lyon (69M)", "president": "Bruno Bernard", "party": "EELV", "population": 1416545, "budget": "3.90 B€" },
  { "department": "Haute-Saône (70)", "president": "Yves Krattinger", "party": "PS", "population": 234296, "budget": "270 M€" },
  { "department": "Saône-et-Loire (71)", "president": "André Accary", "party": "DVD", "population": 549288, "budget": "635 M€" },
  { "department": "Sarthe (72)", "president": "Dominique Le Mèner", "party": "DVD", "population": 566058, "budget": "655 M€" },
  { "department": "Savoie (73)", "president": "Hervé Gaymard", "party": "LR", "population": 442468, "budget": "515 M€" },
  { "department": "Haute-Savoie (74)", "president": "Martial Saddier", "party": "LR", "population": 841482, "budget": "980 M€" },
  { "department": "Paris (75)", "president": "Anne Hidalgo", "party": "PS", "population": 2133111, "budget": "10.5 B€" },
  { "department": "Seine-Maritime (76)", "president": "Bertrand Bellanger", "party": "DVD", "population": 1255918, "budget": "1.45 B€" },
  { "department": "Seine-et-Marne (77)", "president": "Jean-François Parigi", "party": "LR", "population": 1438100, "budget": "1.65 B€" },
  { "department": "Yvelines (78)", "president": "Pierre Bédier", "party": "LR", "population": 1456365, "budget": "1.70 B€" },
  { "department": "Deux-Sèvres (79)", "president": "Coralie Dénoues", "party": "DVD", "population": 374587, "budget": "435 M€" },
  { "department": "Somme (80)", "president": "Stéphane Haussoulier", "party": "DVD", "population": 566223, "budget": "655 M€" },
  { "department": "Tarn (81)", "president": "Christophe Ramond", "party": "PS", "population": 393572, "budget": "455 M€" },
  { "department": "Tarn-et-Garonne (82)", "president": "Michel Weill", "party": "PRG", "population": 263347, "budget": "305 M€" },
  { "department": "Var (83)", "president": "Jean-Louis Masson", "party": "LR", "population": 1095337, "budget": "1.25 B€" },
  { "department": "Vaucluse (84)", "president": "Dominique Santoni", "party": "PS", "population": 564566, "budget": "655 M€" },
  { "department": "Vendée (85)", "president": "Alain Leboeuf", "party": "LR", "population": 693676, "budget": "800 M€" },
  { "department": "Vienne (86)", "president": "Alain Pichon", "party": "DVD", "population": 439385, "budget": "510 M€" },
  { "department": "Haute-Vienne (87)", "president": "Jean-Claude Leblois", "party": "PS", "population": 371583, "budget": "430 M€" },
  { "department": "Vosges (88)", "president": "François Vannson", "party": "DVD", "population": 360670, "budget": "415 M€" },
  { "department": "Yonne (89)", "president": "Patrick Gendraud", "party": "LR", "population": 333385, "budget": "385 M€" },
  { "department": "Territoire de Belfort (90)", "president": "Florian Bouquet", "party": "LR", "population": 139654, "budget": "165 M€" },
  { "department": "Essonne (91)", "president": "François Durovray", "party": "LR", "population": 1305327, "budget": "1.50 B€" },
  { "department": "Hauts-de-Seine (92)", "president": "Georges Siffredi", "party": "LR", "population": 1635291, "budget": "2.20 B€" },
  { "department": "Seine-Saint-Denis (93)", "president": "Stéphane Troussel", "party": "PS", "population": 1668670, "budget": "2.10 B€" },
  { "department": "Val-de-Marne (94)", "president": "Olivier Capitanio", "party": "LR", "population": 1415367, "budget": "1.80 B€" },
  { "department": "Val-d'Oise (95)", "president": "Marie-Christine Cavecchi", "party": "LR", "population": 1256607, "budget": "1.45 B€" },
  { "department": "Guadeloupe (971)", "president": "Guy Losbar", "party": "GUSR", "population": 384315, "budget": "650 M€" },
  { "department": "Martinique (972)", "president": "Serge Letchimy", "party": "PPM", "population": 352596, "budget": "600 M€" },
  { "department": "Guyane (973)", "president": "Gabriel Serville", "party": "PeP-G", "population": 286618, "budget": "550 M€" },
  { "department": "La Réunion (974)", "president": "Cyrille Melchior", "party": "DVD", "population": 871157, "budget": "1.30 B€" },
  { "department": "Mayotte (976)", "president": "Ben Issa Ousseni", "party": "LR", "population": 288926, "budget": "450 M€" }
];

const formatPop = (n) => {
    if (n >= 1000000) return (n / 1000000).toFixed(1) + "M";
    return (n / 1000).toFixed(0) + "K";
};

const formatBudget = (b) => {
    return b.replace(" B€", " Md€");
};

const formattedData = rawData.map(d => ({
    name: d.department,
    president: d.president,
    party: d.party,
    budget: formatBudget(d.budget),
    population: formatPop(d.population)
}));

console.log(JSON.stringify(formattedData, null, 2));
